export const PATH = Object.freeze({
  MAIN: '/',
  LOGIN: '/login',
  MEMBER_LIST: '/member/list',
  CARE_LIST: '/care/list',
  CARE_ADD: '/care/add',
  CARE_EDIT: '/care/edit/:id',
  PREMIUM_LIST: '/premium/list',
  PREMIUM_ADD: '/premium/add',
  PREMIUM_EDIT: '/premium/edit/:id',
  YOUTUBE_LIST: '/youtube/list',
  YOUTUBE_ADD: '/youtube/add',
  YOUTUBE_EDIT: '/youtube/edit/:id',
  BANNER_LIST: '/banner/list',
  BANNER_ADD: '/banner/add',
  BANNER_EDIT: '/banner/edit/:id',
  ADMIN_LIST: '/admin/list',
  ADMIN_ADD: '/admin/add',
  ADMIN_EDIT: '/admin/edit/:id',
  REVIEW_LIST: '/review/list',
});
